/*
 * This file is generated by jOOQ.
 */
package com.example.book_management.jooq


import com.example.book_management.jooq.tables.Authors
import com.example.book_management.jooq.tables.BookAuthors
import com.example.book_management.jooq.tables.Books
import com.example.book_management.jooq.tables.FlywaySchemaHistory

import kotlin.collections.List

import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.DSL
import org.jooq.impl.SchemaImpl


/**
 * standard public schema
 */
@Suppress("warnings")
open class Public : SchemaImpl(DSL.name("public"), DefaultCatalog.DEFAULT_CATALOG, DSL.comment("standard public schema")) {
    companion object {

        /**
         * The reference instance of <code>public</code>
         */
        val PUBLIC: Public = Public()
    }

    /**
     * The table <code>public.authors</code>.
     */
    val AUTHORS: Authors get() = Authors.AUTHORS

    /**
     * The table <code>public.book_authors</code>.
     */
    val BOOK_AUTHORS: BookAuthors get() = BookAuthors.BOOK_AUTHORS

    /**
     * The table <code>public.books</code>.
     */
    val BOOKS: Books get() = Books.BOOKS

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    val FLYWAY_SCHEMA_HISTORY: FlywaySchemaHistory get() = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        Authors.AUTHORS,
        BookAuthors.BOOK_AUTHORS,
        Books.BOOKS,
        FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY
    )
}
