/*
 * This file is generated by jOOQ.
 */
package com.example.book_management.jooq.tables


import com.example.book_management.jooq.Public
import com.example.book_management.jooq.keys.BOOKS_PKEY
import com.example.book_management.jooq.keys.BOOK_AUTHORS__FK_BOOK_AUTHORS_BOOK
import com.example.book_management.jooq.tables.Authors.AuthorsPath
import com.example.book_management.jooq.tables.BookAuthors.BookAuthorsPath
import com.example.book_management.jooq.tables.records.BooksRecord

import java.time.LocalDateTime

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Check
import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableLike
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class Books(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, BooksRecord>?,
    parentPath: InverseForeignKey<out Record, BooksRecord>?,
    aliased: Table<BooksRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<BooksRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.books</code>
         */
        val BOOKS: Books = Books()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<BooksRecord> = BooksRecord::class.java

    /**
     * The column <code>public.books.id</code>.
     */
    val ID: TableField<BooksRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.books.title</code>.
     */
    val TITLE: TableField<BooksRecord, String?> = createField(DSL.name("title"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>public.books.price</code>.
     */
    val PRICE: TableField<BooksRecord, Int?> = createField(DSL.name("price"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.books.publication_status</code>.
     */
    val PUBLICATION_STATUS: TableField<BooksRecord, String?> = createField(DSL.name("publication_status"), SQLDataType.VARCHAR(20).nullable(false), this, "")

    /**
     * The column <code>public.books.created_at</code>.
     */
    val CREATED_AT: TableField<BooksRecord, LocalDateTime?> = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "")

    /**
     * The column <code>public.books.updated_at</code>.
     */
    val UPDATED_AT: TableField<BooksRecord, LocalDateTime?> = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "")

    private constructor(alias: Name, aliased: Table<BooksRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<BooksRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<BooksRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.books</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.books</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.books</code> table reference
     */
    constructor(): this(DSL.name("books"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, BooksRecord>?, parentPath: InverseForeignKey<out Record, BooksRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, BOOKS, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class BooksPath : Books, Path<BooksRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, BooksRecord>?, parentPath: InverseForeignKey<out Record, BooksRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<BooksRecord>): super(alias, aliased)
        override fun `as`(alias: String): BooksPath = BooksPath(DSL.name(alias), this)
        override fun `as`(alias: Name): BooksPath = BooksPath(alias, this)
        override fun `as`(alias: Table<*>): BooksPath = BooksPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<BooksRecord> = BOOKS_PKEY

    private lateinit var _bookAuthors: BookAuthorsPath

    /**
     * Get the implicit to-many join path to the
     * <code>public.book_authors</code> table
     */
    fun bookAuthors(): BookAuthorsPath {
        if (!this::_bookAuthors.isInitialized)
            _bookAuthors = BookAuthorsPath(this, null, BOOK_AUTHORS__FK_BOOK_AUTHORS_BOOK.inverseKey)

        return _bookAuthors;
    }

    val bookAuthors: BookAuthorsPath
        get(): BookAuthorsPath = bookAuthors()

    /**
     * Get the implicit many-to-many join path to the
     * <code>public.authors</code> table
     */
    val authors: AuthorsPath
        get(): AuthorsPath = bookAuthors().authors()
    override fun getChecks(): List<Check<BooksRecord>> = listOf(
        Internal.createCheck(this, DSL.name("books_price_check"), "((price >= 0))", true)
    )
    override fun `as`(alias: String): Books = Books(DSL.name(alias), this)
    override fun `as`(alias: Name): Books = Books(alias, this)
    override fun `as`(alias: Table<*>): Books = Books(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Books = Books(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Books = Books(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Books = Books(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Books = Books(qualifiedName, if (aliased()) this else null, Internal.condition(this, condition))

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Books = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Books = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Books = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Books = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Books = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Books = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Books = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: TableLike<*>): Books = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: TableLike<*>): Books = where(DSL.notExists(select))
}
